sudo: required
services:
  - docker

before_install:
  - docker build -t dollypizzle/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dollypizzle/docker-react yarn run test -- --coverage
