sudo: required
services:
  - docker

before_install:
  - docker build -t dollypizzle/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dollypizzle/docker-react yarn run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-092749212479"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
